Add null to LDEvaluationDetail.reason type
launchdarkly/js-sdk-common pull request #31
Opened 2020-09-15 18:55 UTC by msiadak

**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [ ] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

Provide links to any issues in this repository or elsewhere relating to this pull request.

**Describe the solution you've provided**

Provide a clear and concise description of what you expect to happen.

**Describe alternatives you've considered**

Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

Add any other context about the pull request here.

2020-10-15 00:29 UTC, bwoskow-ld requested changes
Hi @msiadak ,

Thanks for the correction! You're right that `reason` can be `null`.

I made a suggestion to your typedoc and also changed your target branch to `contrib` (instead of `master`) so that we have better control over when and how this becomes available to customers. Other than that this looks good to me.

2020-10-15 00:29 UTC, bwoskow-ld commented on typings.d.ts
> +     * Will be `null` if the `evaluationReasons` client option is `false`.
Let's change this to:

```suggestion
     * Will be `null` if `[[LDOptions.evaluationReasons]]` is `false`.
```

2020-10-15 00:49 UTC, msiadak commented
Cool - thanks for the feedback.

2020-10-15 18:19 UTC, bwoskow-ld approved these changes

2020-10-15 18:19 UTC, bwoskow-ld commented
Looks good. We'll include this in the next library release, to be included in the subsequent SDK releases.

2020-10-15 18:20 UTC, merged

2020-10-16 23:36 UTC, bwoskow-ld commented
Hi @msiadak ,

Sorry to be the bearer of bad news, but we hit a snag after merging your changes. We believe that this one-line change may, in fact, be a breaking change -- even though you correctly pointed out that it fixes an incorrect type definition.

As an example of the breakage, take a look at [this test code](https://github.com/launchdarkly/js-sdk-common/blob/master/test-types.ts#L56). Here we have a file used for test purposes where we compile and use our types to make sure they're correct. After merging this PR, this test file no longer compiles because `detailReason` is now of type `ld.LDEvaluationReason | null` instead of `ld.LDEvaluationReason`.

We should have noticed this breakage prior to merging your pull request. Unfortunately we hadn't enabled the option on our CircleCI configuration to allow forked pull requests to build for this repository; this configuration change has since been applied. Had this configuration been in place previously, we would have noticed the failing test prior to accepting the pull request.

At this time I've reverted your change on the upstream branch.

Let me know what you think.

Cheers,
Ben

2020-11-17 20:58 UTC, bwoskow-ld commented
Hi again, @msiadak,

While I had to revert your contribution for the reason mentioned above, the SDK team continued the conversation internally and identified a backwards-compatible way to make this change. The type definition is now fixed in [`launchdarkly-js-sdk-common` version 3.2.11](https://github.com/launchdarkly/js-sdk-common/releases/tag/3.2.11) which is available in [`launchdarkly-js-client-sdk` version 2.18.3](https://github.com/launchdarkly/js-client-sdk/releases/tag/2.18.3), [`launchdarkly-react-client-sdk` version 2.21.0](https://github.com/launchdarkly/react-client-sdk/releases/tag/2.21.0), and [`launchdarkly-electron-client-sdk` version 1.5.7](https://github.com/launchdarkly/electron-client-sdk/releases/tag/1.5.7).

Cheers,
@bwoskow-ld

2020-11-17 21:03 UTC, msiadak commented
Cool, thanks for the update!